### ISSUE TITLE
使用px2rem-loader构建失败

### ISSUE THREAD

**Issue by ZYSHINee** [cpselvis/geektime-webpack-course#1]
代码如视频中一样，结果编译时报错，错误如下：

ERROR in ./src/search.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/px2rem-loader/index.js):
Error: undefined:6:5: missing '}'
    at error (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:260:26)
    at rule (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:561:21)
    at rules (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:118:70)
    at stylesheet (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/Users/zhangyong/Desktop/webpack-demo/node_modules/css/lib/parse/index.js:565:20)
    at Px2rem.generateRem (/Users/zhangyong/Desktop/webpack-demo/node_modules/px2rem/lib/px2rem.js:70:20)
    at Object.module.exports (/Users/zhangyong/Desktop/webpack-demo/node_modules/px2rem-loader/lib/px2rem-loader.js:7:38)
    at runLoaders (/Users/zhangyong/Desktop/webpack-demo/node_modules/webpack/lib/NormalModule.js:302:20)
    at /Users/zhangyong/Desktop/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/zhangyong/Desktop/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/zhangyong/Desktop/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/zhangyong/Desktop/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/zhangyong/Desktop/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/zhangyong/Desktop/webpack-demo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/zhangyong/Desktop/webpack-demo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/zhangyong/Desktop/webpack-demo/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by cpselvis** [comment]
从这个出错提示上看，应该是你的 webpack 配置里面有语法错误吧。报错信息是在：ERROR in ./src/search.less

应该是 less 语法有问题
